model {
  file: "model.sdf"
}
name: "Olive_Kids_Mermaids_Pack_n_Snack_Backpack"
description: "Olive Kids Mermaids Pack \'n Snack Backpack"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Wildkin"
}
annotations {
  key: "gtin"
  value: "097277400817"
}
annotations {
  key: "mpn"
  value: "40081"
}
annotations {
  key: "sku"
  value: "40081"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Bag"
}
