model {
  file: "model.sdf"
}
name: "Crayola_Washable_Sidewalk_Chalk_16_pack"
description: "Crayola Washable Sidewalk Chalk - 16 pack"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Crayola"
}
annotations {
  key: "gtin"
  value: "00071662612160"
}
annotations {
  key: "sku"
  value: "00071662612160"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
