model {
  file: "model.sdf"
}
name: "Office_Depot_HP_74XL75_Remanufactured_Ink_Cartridges_BlackTriColor_2_count"
description: "Office Depot (HP 74XL/75) Remanufactured Ink Cartridges - Black/Tri-Color - 2 count"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Office"
}
annotations {
  key: "gtin"
  value: "00841992063495"
}
annotations {
  key: "sku"
  value: "00841992063495"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
