model {
  file: "model.sdf"
}
name: "Reebok_BREAKPOINT_MID"
description: "Reebok BREAKPOINT MID"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Reebok"
}
annotations {
  key: "mpn"
  value: "j98744"
}
annotations {
  key: "sku"
  value: "J98744"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Shoe"
}
