model {
  file: "model.sdf"
}
name: "Office_Depot_Canon_CLI_8Y_Ink_Cartridge_Yellow_0623B002"
description: "Office Depot Canon CLI 8Y Ink Cartridge, Yellow (0623B002)"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Office Depot"
}
annotations {
  key: "gtin"
  value: "00841992044944"
}
annotations {
  key: "sku"
  value: "00841992044944"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Consumer Goods"
}
