model {
  file: "model.sdf"
}
name: "Mist_Wipe_Warmer"
description: "Mist Wipe Warmer"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Munchkin"
}
annotations {
  key: "gtin"
  value: "735282436819"
}
annotations {
  key: "mpn"
  value: "43691"
}
annotations {
  key: "sku"
  value: "43681"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
