model {
  file: "model.sdf"
}
name: "Mens_Billfish_Slip_On_in_Coffee_e8bPKE9Lfgo"
description: "Men\'s Billfish Slip On in Coffee\nMen\'s Billfish Slip On"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Sperry Top-Sider"
}
annotations {
  key: "gtin"
  value: "044211829555"
}
annotations {
  key: "mpn"
  value: "0852863"
}
annotations {
  key: "sku"
  value: "BillfishSlipOnF09-7"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
  first: "Shoe"
}
